-- Add permanent join token to boxes
-- This token is used for the shareable box join link (/join/<token>)
-- It never expires and can be regenerated by the owner if needed

ALTER TABLE boxes
  ADD COLUMN IF NOT EXISTS join_token uuid DEFAULT gen_random_uuid() NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS boxes_join_token_idx ON boxes (join_token);
